name: Sync OpenAPI

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
  push:
    branches:
    - main

jobs:
  sync:
    uses: dappsteros-io/github/.github/workflows/sync_openapi.yml@main
    with:
      project-name: dappsteros-user-service
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
